version: '3'

services:
  app:
    build:
      context: .
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
    volumes:
      - ./docker/database.yml:/app/config/database.yml
      - ./docker/unicorn.rb:/app/config/unicorn.rb
      - unicorn:/unicorn
      - assets:/assets
    depends_on:
      - db

  nginx:
    image: nginx
    depends_on: [app]
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/public:ro
      - unicorn:/unicorn
      - assets:/public
    labels:
      - traefik.frontend.rule=Host:localhost

  db:
    image: mysql:5.7.21
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: smart
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: smart
      MYSQL_USER: smart
      MYSQL_PASSWORD: smart
    volumes:
      - db:/var/lib/mysql


volumes:
  db:
  unicorn:
  assets:
